//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-ssd1-SSD_SERVICE_ID_sd_OGaR2WG22Z1Zwrxk
import { ssd1 as SSD_SERVICE_ID_sd_OGaR2WG22Z1Zwrxk } from './sd-services/ssd1';

export const UserRoutes = [
    //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-ssd1-SSD_SERVICE_ID_sd_OGaR2WG22Z1Zwrxk
SSD_SERVICE_ID_sd_OGaR2WG22Z1Zwrxk,
];